respond_to_idea_business_consultant:
  description: >
    As a business consultant, analyze the from your own perspective.
  expected_output: >
    A list of considerations including positives, negatives and adjecent ideas.
  agent: business_consultant

respond_to_idea_project_manager:
  description: >
    As a project manager, evaluate the idea from your own perspective.
  expected_output: >
    A list of considerations including positives, negatives and adjecent ideas.
  agent: project_manager

summarize:
  description: >
    Give a consise summary the focus group output.
  expected_output: >
    For each participant list the main point they raised. Then continue with the most important points which the focus group agreed upon.
  agent: summarizer

discuss_idea:
  description: >
    Discuss the following idea with all agents, then summarize the key points mentioned in the discussion. The idea: {idea}
